# Generated by Django 5.2.5 on 2025-08-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('os', models.CharField(max_length=255)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('ram_gb', models.FloatField()),
                ('used_ram_gb', models.FloatField()),
                ('available_ram_gb', models.FloatField()),
                ('storage_total_gb', models.FloatField()),
                ('storage_used_gb', models.FloatField()),
                ('storage_free_gb', models.FloatField()),
                ('cpu_freq_mhz', models.FloatField(blank=True, null=True)),
                ('process_count', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.host')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('cmdline', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitor.snapshot')),
            ],
        ),
    ]
