# Generated by Django 5.2.5 on 2025-08-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('process_count', models.PositiveIntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.host')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('cmdline', models.TextField(blank=True, default='')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitor.snapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['host', '-captured_at'], name='monitor_sna_host_id_0bd121_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'ppid'], name='monitor_pro_snapsho_a44cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'pid'], name='monitor_pro_snapsho_b954ff_idx'),
        ),
    ]
